/**
 * Apply contract for ArborCTL from nxt VFD tab.
 * Keep file format / M98 sequence aligned with ArborCTL dwc-plugin/dwc-src/arborctlApply.ts.
 */

export const ARBORCTL_USER_VARS_PATH = '0:/sys/arborctl-user-vars.g'

export const FALLBACK_ARBOR_MODELS = [
  'Shihlin SL3',
  'Huanyang HY02D223',
  'Yalang YL620-A',
  'Manual Modbus (experimental)',
  'TH Servo (preliminary)',
  'H100'
] as const

export const FALLBACK_ARBOR_INTERNAL_NAMES = [
  'shihlin-sl3',
  'huanyang-hy02d223b',
  'yalang-yl620a',
  'modbus-manual-experimental',
  'th-servo',
  'h100'
] as const

export const MANUAL_MODBUS_INDEX = 3

/** RRF 3.7: P0/P1 are USB CDC. Only hardware UARTs are selectable for Modbus. */
export const ARBOR_DEFAULT_UART_CHANNEL = 2

export const ARBOR_UART_CHANNELS: Array<{ text: string; value: number }> = [
  { text: 'P2 (first UART / RS485)', value: 2 },
  { text: 'P3 (second UART / header)', value: 3 }
]

export function isArborUartChannel(channel: number): boolean {
  return channel === 2 || channel === 3
}

export function clampArborUartChannel(channel: number): number {
  return isArborUartChannel(channel) ? channel : ARBOR_DEFAULT_UART_CHANNEL
}

export interface ArborCtlApplyForm {
  channel: number
  baud: number
  address: number
  typeIndex: number
  spindleId: number
  motorW: number
  motorPoles: number
  motorV: number
  motorF: number
  motorI: number
  motorR: number
  accelSec: number
  decelSec: number
  manualSpec?: number[]
}

export interface ArborCtlHzLimits {
  t: number
  e: number
}

export function arborInternalName(
  typeIndex: number,
  internalNames?: string[] | null
): string {
  if (Array.isArray(internalNames) && internalNames[typeIndex] != null) {
    return String(internalNames[typeIndex])
  }
  return FALLBACK_ARBOR_INTERNAL_NAMES[typeIndex] ?? FALLBACK_ARBOR_INTERNAL_NAMES[0]
}

export function arborTypeName(typeIndex: number, models?: string[] | null): string {
  if (Array.isArray(models) && models[typeIndex] != null) {
    return String(models[typeIndex])
  }
  return FALLBACK_ARBOR_MODELS[typeIndex] ?? `Type ${typeIndex}`
}

export function buildArborCtlUserVarsFile(
  f: ArborCtlApplyForm,
  hz: ArborCtlHzLimits,
  typeName: string
): string {
  const channel = clampArborUartChannel(f.channel)
  const lines = [
    '; ArborCtl User Variables',
    ';',
    '; This file is automatically generated by the ArborCTL DWC plugin / nxt VFD tab.',
    '; You can edit this file manually at your own risk.',
    '',
    '; ArborCtl Configuration',
    '; UART Configuration',
    `M575 P${channel} B${f.baud} S7 ; Configure UART for Modbus RTU`,
    '',
    '; VFD Configuration',
    `; Type: ${typeName} Channel: ${channel} Address: ${f.address}`,
    `set global.arborVFDConfig[${f.spindleId}] = {${f.typeIndex}, ${channel}, ${f.address}} ; VFD configuration`,
    `set global.arborMotorSpec[${f.spindleId}] = {${f.motorW}, ${f.motorPoles}, ${f.motorV}, ${f.motorF}, ${f.motorI}, ${f.motorR}} ; Wizard motor (kW,poles,V,Hz,A,RPM)`,
    `set global.arborWizardFreqLimits[${f.spindleId}] = {${hz.t}, ${hz.e}} ; Min/max Hz from spindle limits`,
    `set global.arborWizardRamp[${f.spindleId}] = {${f.accelSec}, ${f.decelSec}} ; Accel/decel seconds`,
    ''
  ]
  if (f.typeIndex === MANUAL_MODBUS_INDEX && Array.isArray(f.manualSpec)) {
    lines.push(
      `set global.arborModbusManualSpec[${f.spindleId}] = {${f.manualSpec.join(
        ', '
      )}} ; Manual Modbus (experimental)`,
      ''
    )
  }
  return lines.join('\n')
}

export function buildArborCtlConfigCode(
  f: ArborCtlApplyForm,
  hz: ArborCtlHzLimits,
  internalName: string
): string {
  const channel = clampArborUartChannel(f.channel)
  return (
    `M98 P"arborctl/${internalName}/config.g" B${f.baud} C${channel} A${f.address} S${f.spindleId} ` +
    `W${f.motorW} U${f.motorPoles} V${f.motorV} F${f.motorF} I${f.motorI} R${f.motorR} ` +
    `T${hz.t} E${hz.e} J${f.accelSec} K${f.decelSec}`
  )
}
