/**
 * Generate custom machine pack overlay files for hybrid SD persistence.
 */
import type { NxtUserConfigDraft } from './nxtUserVarsPersistence'
import {
  buildAllCustomHomingFiles,
  homeAtFromDraft,
  type CustomHomeAt
} from './nxtCustomHoming'

export type CustomPackFileMap = Record<string, string>

/** Parse "0:1,1:1,2:0" → [{ drive: 0, dir: 1 }, ...] */
export function parseDriveDirs(raw: string | null | undefined): Array<{ drive: number; dir: 0 | 1 }> {
  if (raw == null || !String(raw).trim()) {
    return []
  }
  const out: Array<{ drive: number; dir: 0 | 1 }> = []
  for (const part of String(raw).split(',')) {
    const bit = part.trim()
    if (!bit) continue
    const [dStr, sStr] = bit.split(':')
    const drive = Number(dStr)
    const dir = Number(sStr)
    if (!Number.isInteger(drive) || drive < 0) continue
    if (dir !== 0 && dir !== 1) continue
    out.push({ drive, dir: dir as 0 | 1 })
  }
  return out
}

/** Build compact nxtCustomDriveDirs from map. */
export function formatDriveDirs(entries: Array<{ drive: number; dir: 0 | 1 }>): string | null {
  if (!entries.length) return null
  const sorted = [...entries].sort((a, b) => a.drive - b.drive)
  return sorted.map((e) => `${e.drive}:${e.dir}`).join(',')
}

/** Parse "0" or "2:3" into drive indices. */
export function parseDriveList(raw: string | null | undefined): number[] {
  if (raw == null || !String(raw).trim()) return []
  return String(raw)
    .split(':')
    .map((s) => Number(s.trim()))
    .filter((n) => Number.isInteger(n) && n >= 0)
}

export function formatDriveList(drives: number[]): string | null {
  if (!drives.length) return null
  return drives.join(':')
}

function pinLiteral(pin: string): string {
  return pin.replace(/"/g, '').trim()
}

export function buildCustomDrivesOverlayG(config: NxtUserConfigDraft): string {
  const lines: string[] = [
    '; drives-overlay.g — generated by nxt Configuration (custom platform)',
    '; Overrides board-pack M569 / M584 / M906 when set.',
    ''
  ]

  const dirs = parseDriveDirs(config.nxtCustomDriveDirs)
  if (dirs.length) {
    lines.push('; M569 drive directions')
    for (const { drive, dir } of dirs) {
      lines.push(`M569 P${drive} S${dir}`)
    }
    lines.push('')
  }

  const xd = config.nxtCustomXDrives
  const yd = config.nxtCustomYDrives
  const zd = config.nxtCustomZDrives
  if (xd && yd && zd) {
    lines.push('; M584 axis map')
    lines.push(`M584 X${xd} Y${yd} Z${zd}`)
    lines.push('')
  }

  const xc = config.nxtCustomXCurrent
  const yc = config.nxtCustomYCurrent
  const zc = config.nxtCustomZCurrent
  if (xc != null && yc != null && zc != null) {
    lines.push('; M906 currents (mA)')
    lines.push(`M906 X${xc} Y${yc} Z${zc}`)
    lines.push('')
  }

  const bx = config.nxtCustomXBacklash
  const by = config.nxtCustomYBacklash
  const bz = config.nxtCustomZBacklash
  const ba = config.nxtCustomABacklash
  if (bx != null || by != null || bz != null || ba != null) {
    lines.push('; M425 backlash compensation')
    const parts: string[] = []
    if (bx != null) parts.push(`X${bx}`)
    if (by != null) parts.push(`Y${by}`)
    if (bz != null) parts.push(`Z${bz}`)
    if (ba != null) parts.push(`A${ba}`)
    lines.push(`M425 ${parts.join(' ')}`)
    lines.push('')
  }

  if (lines.length <= 3) {
    lines.push('; No custom drive overrides set — board pack values remain.')
  }

  return lines.join('\n')
}

export function buildCustomEndstopsG(config: NxtUserConfigDraft): string {
  const lines: string[] = [
    '; endstops.g — generated by nxt Configuration (custom platform)',
    '; M574 pin + side after board pack.',
    ''
  ]

  const axes: Array<{
    letter: 'X' | 'Y' | 'Z'
    pin: string | null
    homeAt: number | null
  }> = [
    { letter: 'X', pin: config.nxtCustomXEndstopPin, homeAt: config.nxtCustomXHomeAt },
    { letter: 'Y', pin: config.nxtCustomYEndstopPin, homeAt: config.nxtCustomYHomeAt },
    { letter: 'Z', pin: config.nxtCustomZEndstopPin, homeAt: config.nxtCustomZHomeAt }
  ]

  let any = false
  for (const a of axes) {
    if (a.pin && (a.homeAt === 1 || a.homeAt === 2)) {
      lines.push(`M574 ${a.letter}${a.homeAt} S1 P"${pinLiteral(a.pin)}"`)
      any = true
    }
  }

  if (!any) {
    lines.push('; No custom endstop overrides — board pack M574 remains.')
  }

  lines.push('')
  return lines.join('\n')
}

export function buildCustomStepsG(config: NxtUserConfigDraft): string {
  const xs = config.nxtCustomXSteps
  const ys = config.nxtCustomYSteps
  const zs = config.nxtCustomZSteps
  const as = config.nxtCustomASteps
  if (xs != null && ys != null && zs != null) {
    const aPart = as != null ? ` A${as}` : ''
    return [
      '; steps.g — generated by nxt Configuration / Calibration (custom platform)',
      `M92 X${xs} Y${ys} Z${zs}${aPart}`,
      ''
    ].join('\n')
  }
  return [
    '; steps.g — generated stub (defaults; set nxtCustom*Steps in Configuration)',
    'M92 X800 Y800 Z800',
    ''
  ].join('\n')
}

export function buildCustomLimitsG(config: NxtUserConfigDraft): string {
  const { nxtCustomXMin: xmin, nxtCustomXMax: xmax } = config
  const { nxtCustomYMin: ymin, nxtCustomYMax: ymax } = config
  const { nxtCustomZMin: zmin, nxtCustomZMax: zmax } = config
  if (
    xmin == null ||
    xmax == null ||
    ymin == null ||
    ymax == null ||
    zmin == null ||
    zmax == null
  ) {
    return [
      '; limits.g — generated stub; set all nxtCustom* Min/Max in Configuration',
      'echo "[nxt] custom limits: set all nxtCustom* Min/Max in Configuration"',
      'M117 "nxt custom limits unset"',
      'M99',
      ''
    ].join('\n')
  }
  return [
    '; limits.g — generated by nxt Configuration (custom platform)',
    `M208 X${xmin} Y${ymin} Z${zmin} S1`,
    `M208 X${xmax} Y${ymax} Z${zmax} S0`,
    ''
  ].join('\n')
}

export function customHomingInputFromDraft(config: NxtUserConfigDraft): {
  xHomeAt: CustomHomeAt
  yHomeAt: CustomHomeAt
  zHomeAt: CustomHomeAt
} {
  return {
    xHomeAt: homeAtFromDraft(config.nxtCustomXHomeAt, 1),
    yHomeAt: homeAtFromDraft(config.nxtCustomYHomeAt, 1),
    zHomeAt: homeAtFromDraft(config.nxtCustomZHomeAt, 2)
  }
}

/** All pack + home files to upload for custom platform Save. */
export function buildCustomPackFiles(config: NxtUserConfigDraft): CustomPackFileMap {
  const homes = buildAllCustomHomingFiles(customHomingInputFromDraft(config))
  return {
    'drives-overlay.g': buildCustomDrivesOverlayG(config),
    'endstops.g': buildCustomEndstopsG(config),
    'steps.g': buildCustomStepsG(config),
    'limits.g': buildCustomLimitsG(config),
    ...homes
  }
}

export function validateCustomMachineDraft(config: NxtUserConfigDraft): string[] {
  const errors: string[] = []
  const checkMinMax = (min: number | null, max: number | null, label: string) => {
    if (min != null && max != null && !(min < max)) {
      errors.push(`${label}: min must be less than max`)
    }
  }
  checkMinMax(config.nxtCustomXMin, config.nxtCustomXMax, 'X')
  checkMinMax(config.nxtCustomYMin, config.nxtCustomYMax, 'Y')
  checkMinMax(config.nxtCustomZMin, config.nxtCustomZMax, 'Z')

  for (const [label, steps] of [
    ['X steps', config.nxtCustomXSteps],
    ['Y steps', config.nxtCustomYSteps],
    ['Z steps', config.nxtCustomZSteps]
  ] as const) {
    if (steps != null && !(steps > 0)) errors.push(`${label} must be > 0`)
  }

  for (const [label, cur] of [
    ['X current', config.nxtCustomXCurrent],
    ['Y current', config.nxtCustomYCurrent],
    ['Z current', config.nxtCustomZCurrent]
  ] as const) {
    if (cur != null && !(cur > 0)) errors.push(`${label} must be > 0`)
  }

  for (const [label, ha] of [
    ['X HomeAt', config.nxtCustomXHomeAt],
    ['Y HomeAt', config.nxtCustomYHomeAt],
    ['Z HomeAt', config.nxtCustomZHomeAt]
  ] as const) {
    if (ha != null && ha !== 1 && ha !== 2) errors.push(`${label} must be 1 (min) or 2 (max)`)
  }

  const used = new Set<number>()
  for (const [label, raw] of [
    ['X drives', config.nxtCustomXDrives],
    ['Y drives', config.nxtCustomYDrives],
    ['Z drives', config.nxtCustomZDrives]
  ] as const) {
    const list = parseDriveList(raw)
    for (const d of list) {
      if (used.has(d)) errors.push(`Drive ${d} mapped more than once (${label})`)
      used.add(d)
    }
  }

  const dirs = parseDriveDirs(config.nxtCustomDriveDirs)
  for (const d of used) {
    if (!dirs.some((e) => e.drive === d)) {
      // Direction optional until drives are set; warn only if dirs string present
    }
  }
  if (dirs.length && used.size) {
    for (const d of used) {
      if (!dirs.some((e) => e.drive === d)) {
        errors.push(`Drive ${d} is mapped but missing from M569 directions`)
      }
    }
  }

  return errors
}

export const CUSTOM_PACK_SD_DIR = '0:/sys/nxt-config/machine/custom'
