/**
 * Generate custom machine pack overlay files for hybrid SD persistence.
 * Overlays are uploaded to 0:/sys/nxt-user-custom/ (survives plugin ZIP reinstall).
 */
import type { NxtUserConfigDraft } from './nxtUserVarsPersistence'
import {
  buildAllCustomHomingFiles,
  homeAtFromDraft,
  type CustomHomeAt
} from './nxtCustomHoming'

export type CustomPackFileMap = Record<string, string>

/** Parse "0:1,1:1,2:0" → [{ drive: 0, dir: 1 }, ...] */
export function parseDriveDirs(raw: string | null | undefined): Array<{ drive: number; dir: 0 | 1 }> {
  if (raw == null || !String(raw).trim()) {
    return []
  }
  const out: Array<{ drive: number; dir: 0 | 1 }> = []
  for (const part of String(raw).split(',')) {
    const bit = part.trim()
    if (!bit) continue
    const [dStr, sStr] = bit.split(':')
    const drive = Number(dStr)
    const dir = Number(sStr)
    if (!Number.isInteger(drive) || drive < 0) continue
    if (dir !== 0 && dir !== 1) continue
    out.push({ drive, dir: dir as 0 | 1 })
  }
  return out
}

/** Build compact nxtCustomDriveDirs from map. */
export function formatDriveDirs(entries: Array<{ drive: number; dir: 0 | 1 }>): string | null {
  if (!entries.length) return null
  const sorted = [...entries].sort((a, b) => a.drive - b.drive)
  return sorted.map((e) => `${e.drive}:${e.dir}`).join(',')
}

/** Parse "0" or "2:3" into drive indices. */
export function parseDriveList(raw: string | null | undefined): number[] {
  if (raw == null || !String(raw).trim()) return []
  return String(raw)
    .split(':')
    .map((s) => Number(s.trim()))
    .filter((n) => Number.isInteger(n) && n >= 0)
}

export function formatDriveList(drives: number[]): string | null {
  if (!drives.length) return null
  return drives.join(':')
}

/** Parse single pin or "+" joined dual-endstop list. */
export function parseEndstopPinList(raw: string | null | undefined): string[] {
  if (raw == null || !String(raw).trim()) return []
  return String(raw)
    .split('+')
    .map((s) => s.replace(/"/g, '').trim())
    .filter((s) => s.length > 0)
}

export function formatEndstopPinList(pins: string[]): string | null {
  const cleaned = pins.map((p) => p.replace(/"/g, '').trim()).filter((p) => p.length > 0)
  if (!cleaned.length) return null
  return cleaned.join('+')
}

function pinLiteral(pin: string): string {
  return pin.replace(/"/g, '').trim()
}

/** True when any A-axis custom field is set (optional A requires a complete set). */
export function customAAxisPartiallyConfigured(config: NxtUserConfigDraft): boolean {
  return (
    config.nxtCustomAMin != null ||
    config.nxtCustomAMax != null ||
    config.nxtCustomASteps != null ||
    config.nxtCustomAHomeAt != null ||
    (config.nxtCustomAEndstopPin != null && String(config.nxtCustomAEndstopPin).trim() !== '') ||
    (config.nxtCustomADrives != null && String(config.nxtCustomADrives).trim() !== '') ||
    config.nxtCustomACurrent != null ||
    config.nxtCustomABacklash != null
  )
}

export function customAAxisFullyConfigured(config: NxtUserConfigDraft): boolean {
  return (
    config.nxtCustomAMin != null &&
    config.nxtCustomAMax != null &&
    config.nxtCustomASteps != null &&
    (config.nxtCustomAHomeAt === 1 || config.nxtCustomAHomeAt === 2) &&
    parseEndstopPinList(config.nxtCustomAEndstopPin).length > 0 &&
    parseDriveList(config.nxtCustomADrives).length > 0 &&
    config.nxtCustomACurrent != null
  )
}

export function buildCustomDrivesOverlayG(config: NxtUserConfigDraft): string {
  const lines: string[] = [
    '; drives-overlay.g — generated by nxt Configuration (custom platform)',
    '; Written to 0:/sys/nxt-user-custom/ (survives plugin ZIP reinstall).',
    '; Overrides board-pack M569 / M584 / M906 when set.',
    ''
  ]

  const dirs = parseDriveDirs(config.nxtCustomDriveDirs)
  if (dirs.length) {
    lines.push('; M569 drive directions')
    for (const { drive, dir } of dirs) {
      lines.push(`M569 P${drive} S${dir}`)
    }
    lines.push('')
  }

  const xDrives = parseDriveList(config.nxtCustomXDrives)
  const yDrives = parseDriveList(config.nxtCustomYDrives)
  const zDrives = parseDriveList(config.nxtCustomZDrives)
  const aDrives = parseDriveList(config.nxtCustomADrives)
  if (xDrives.length && yDrives.length && zDrives.length) {
    lines.push('; M584 axis map')
    const aPart = aDrives.length ? ` A${formatDriveList(aDrives)}` : ''
    lines.push(
      `M584 X${formatDriveList(xDrives)} Y${formatDriveList(yDrives)} Z${formatDriveList(zDrives)}${aPart}`
    )
    lines.push('')
  }

  const xc = config.nxtCustomXCurrent
  const yc = config.nxtCustomYCurrent
  const zc = config.nxtCustomZCurrent
  const ac = config.nxtCustomACurrent
  if (xc != null && yc != null && zc != null) {
    lines.push('; M906 currents (mA)')
    const aPart = ac != null ? ` A${ac}` : ''
    lines.push(`M906 X${xc} Y${yc} Z${zc}${aPart}`)
    lines.push('')
  }

  const bx = config.nxtCustomXBacklash
  const by = config.nxtCustomYBacklash
  const bz = config.nxtCustomZBacklash
  const ba = config.nxtCustomABacklash
  if (bx != null || by != null || bz != null || ba != null) {
    lines.push('; M425 backlash compensation')
    const parts: string[] = []
    if (bx != null) parts.push(`X${bx}`)
    if (by != null) parts.push(`Y${by}`)
    if (bz != null) parts.push(`Z${bz}`)
    if (ba != null) parts.push(`A${ba}`)
    lines.push(`M425 ${parts.join(' ')}`)
    lines.push('')
  }

  if (lines.length <= 4) {
    lines.push('; No custom drive overrides set — board pack values remain.')
  }

  return lines.join('\n')
}

export function buildCustomEndstopsG(config: NxtUserConfigDraft): string {
  const lines: string[] = [
    '; endstops.g — generated by nxt Configuration (custom platform)',
    '; Written to 0:/sys/nxt-user-custom/. Multi-pin: P"pin1+pin2" (order = M584 drives).',
    ''
  ]

  const axes: Array<{
    letter: 'X' | 'Y' | 'Z' | 'A'
    pin: string | null
    homeAt: number | null
  }> = [
    { letter: 'X', pin: config.nxtCustomXEndstopPin, homeAt: config.nxtCustomXHomeAt },
    { letter: 'Y', pin: config.nxtCustomYEndstopPin, homeAt: config.nxtCustomYHomeAt },
    { letter: 'Z', pin: config.nxtCustomZEndstopPin, homeAt: config.nxtCustomZHomeAt },
    { letter: 'A', pin: config.nxtCustomAEndstopPin, homeAt: config.nxtCustomAHomeAt }
  ]

  let any = false
  for (const a of axes) {
    const pins = parseEndstopPinList(a.pin)
    if (pins.length && (a.homeAt === 1 || a.homeAt === 2)) {
      lines.push(`M574 ${a.letter}${a.homeAt} S1 P"${pinLiteral(pins.join('+'))}"`)
      any = true
    }
  }

  if (!any) {
    lines.push('; No custom endstop overrides — board pack M574 remains.')
  }

  lines.push('')
  return lines.join('\n')
}

export function buildCustomStepsG(config: NxtUserConfigDraft): string {
  const xs = config.nxtCustomXSteps
  const ys = config.nxtCustomYSteps
  const zs = config.nxtCustomZSteps
  const as = config.nxtCustomASteps
  if (xs != null && ys != null && zs != null) {
    const aPart = as != null ? ` A${as}` : ''
    return [
      '; steps.g — generated by nxt Configuration / Calibration (custom platform)',
      '; Written to 0:/sys/nxt-user-custom/.',
      `M92 X${xs} Y${ys} Z${zs}${aPart}`,
      ''
    ].join('\n')
  }
  return [
    '; steps.g — generated stub (defaults; set nxtCustom*Steps in Configuration)',
    'M92 X800 Y800 Z800',
    ''
  ].join('\n')
}

export function buildCustomLimitsG(config: NxtUserConfigDraft): string {
  const { nxtCustomXMin: xmin, nxtCustomXMax: xmax } = config
  const { nxtCustomYMin: ymin, nxtCustomYMax: ymax } = config
  const { nxtCustomZMin: zmin, nxtCustomZMax: zmax } = config
  const { nxtCustomAMin: amin, nxtCustomAMax: amax } = config
  if (
    xmin == null ||
    xmax == null ||
    ymin == null ||
    ymax == null ||
    zmin == null ||
    zmax == null
  ) {
    return [
      '; limits.g — generated stub; set all nxtCustom* Min/Max in Configuration',
      'echo "[nxt] custom limits: set all nxtCustom* Min/Max in Configuration"',
      'M117 "nxt custom limits unset"',
      'M99',
      ''
    ].join('\n')
  }
  const lines = [
    '; limits.g — generated by nxt Configuration (custom platform)',
    '; Written to 0:/sys/nxt-user-custom/.',
    `M208 X${xmin} Y${ymin} Z${zmin} S1`,
    `M208 X${xmax} Y${ymax} Z${zmax} S0`
  ]
  if (amin != null && amax != null) {
    lines.push(`M208 A${amin} S1`)
    lines.push(`M208 A${amax} S0`)
  }
  lines.push('')
  return lines.join('\n')
}

export function customHomingInputFromDraft(config: NxtUserConfigDraft): {
  xHomeAt: CustomHomeAt
  yHomeAt: CustomHomeAt
  zHomeAt: CustomHomeAt
  aHomeAt: CustomHomeAt | null
  includeA: boolean
} {
  const includeA = customAAxisFullyConfigured(config)
  return {
    xHomeAt: homeAtFromDraft(config.nxtCustomXHomeAt, 1),
    yHomeAt: homeAtFromDraft(config.nxtCustomYHomeAt, 1),
    zHomeAt: homeAtFromDraft(config.nxtCustomZHomeAt, 2),
    aHomeAt: includeA ? homeAtFromDraft(config.nxtCustomAHomeAt, 1) : null,
    includeA
  }
}

/** All pack + home files to upload for custom platform Save. */
export function buildCustomPackFiles(config: NxtUserConfigDraft): CustomPackFileMap {
  const input = customHomingInputFromDraft(config)
  const homes = buildAllCustomHomingFiles(input)
  return {
    'drives-overlay.g': buildCustomDrivesOverlayG(config),
    'endstops.g': buildCustomEndstopsG(config),
    'steps.g': buildCustomStepsG(config),
    'limits.g': buildCustomLimitsG(config),
    ...homes
  }
}

export function validateCustomMachineDraft(config: NxtUserConfigDraft): string[] {
  const errors: string[] = []

  for (const [label, min, max, steps, homeAt, pin, drives, current] of [
    [
      'X',
      config.nxtCustomXMin,
      config.nxtCustomXMax,
      config.nxtCustomXSteps,
      config.nxtCustomXHomeAt,
      config.nxtCustomXEndstopPin,
      config.nxtCustomXDrives,
      config.nxtCustomXCurrent
    ],
    [
      'Y',
      config.nxtCustomYMin,
      config.nxtCustomYMax,
      config.nxtCustomYSteps,
      config.nxtCustomYHomeAt,
      config.nxtCustomYEndstopPin,
      config.nxtCustomYDrives,
      config.nxtCustomYCurrent
    ],
    [
      'Z',
      config.nxtCustomZMin,
      config.nxtCustomZMax,
      config.nxtCustomZSteps,
      config.nxtCustomZHomeAt,
      config.nxtCustomZEndstopPin,
      config.nxtCustomZDrives,
      config.nxtCustomZCurrent
    ]
  ] as const) {
    if (min == null || max == null) errors.push(`${label}: min and max are required`)
    if (steps == null) errors.push(`${label}: steps/mm is required`)
    if (homeAt !== 1 && homeAt !== 2) errors.push(`${label}: endstop location (min/max) is required`)
    if (parseEndstopPinList(pin).length === 0) errors.push(`${label}: endstop pin(s) required`)
    if (parseDriveList(drives).length === 0) errors.push(`${label}: drive map is required`)
    if (current == null) errors.push(`${label}: motor current is required`)
  }

  const checkMinMax = (min: number | null, max: number | null, label: string) => {
    if (min != null && max != null && !(min < max)) {
      errors.push(`${label}: min must be less than max`)
    }
  }
  checkMinMax(config.nxtCustomXMin, config.nxtCustomXMax, 'X')
  checkMinMax(config.nxtCustomYMin, config.nxtCustomYMax, 'Y')
  checkMinMax(config.nxtCustomZMin, config.nxtCustomZMax, 'Z')
  checkMinMax(config.nxtCustomAMin, config.nxtCustomAMax, 'A')

  for (const [label, steps] of [
    ['X steps', config.nxtCustomXSteps],
    ['Y steps', config.nxtCustomYSteps],
    ['Z steps', config.nxtCustomZSteps],
    ['A steps', config.nxtCustomASteps]
  ] as const) {
    if (steps != null && !(steps > 0)) errors.push(`${label} must be > 0`)
  }

  for (const [label, cur] of [
    ['X current', config.nxtCustomXCurrent],
    ['Y current', config.nxtCustomYCurrent],
    ['Z current', config.nxtCustomZCurrent],
    ['A current', config.nxtCustomACurrent]
  ] as const) {
    if (cur != null && !(cur > 0)) errors.push(`${label} must be > 0`)
  }

  for (const [label, ha] of [
    ['X HomeAt', config.nxtCustomXHomeAt],
    ['Y HomeAt', config.nxtCustomYHomeAt],
    ['Z HomeAt', config.nxtCustomZHomeAt],
    ['A HomeAt', config.nxtCustomAHomeAt]
  ] as const) {
    if (ha != null && ha !== 1 && ha !== 2) errors.push(`${label} must be 1 (min) or 2 (max)`)
  }

  const used = new Set<number>()
  for (const [label, raw] of [
    ['X drives', config.nxtCustomXDrives],
    ['Y drives', config.nxtCustomYDrives],
    ['Z drives', config.nxtCustomZDrives],
    ['A drives', config.nxtCustomADrives]
  ] as const) {
    const list = parseDriveList(raw)
    for (const d of list) {
      if (used.has(d)) errors.push(`Drive ${d} mapped more than once (${label})`)
      used.add(d)
    }
  }

  const dirs = parseDriveDirs(config.nxtCustomDriveDirs)
  if (dirs.length && used.size) {
    for (const d of used) {
      if (!dirs.some((e) => e.drive === d)) {
        errors.push(`Drive ${d} is mapped but missing from M569 directions`)
      }
    }
  }

  // Dual-endstop: pin count should not exceed drive count when both set
  for (const [label, pinRaw, driveRaw] of [
    ['X', config.nxtCustomXEndstopPin, config.nxtCustomXDrives],
    ['Y', config.nxtCustomYEndstopPin, config.nxtCustomYDrives],
    ['Z', config.nxtCustomZEndstopPin, config.nxtCustomZDrives],
    ['A', config.nxtCustomAEndstopPin, config.nxtCustomADrives]
  ] as const) {
    const pins = parseEndstopPinList(pinRaw)
    const drives = parseDriveList(driveRaw)
    if (pins.length > 1 && drives.length > 0 && pins.length !== drives.length) {
      errors.push(
        `${label}: endstop pin count (${pins.length}) should match drive count (${drives.length}) for dual homing`
      )
    }
  }

  if (customAAxisPartiallyConfigured(config) && !customAAxisFullyConfigured(config)) {
    errors.push(
      'A axis: when any A field is set, require min/max, steps, home side, endstop pin(s), drives, and current'
    )
  }

  return errors
}

/** User-owned Custom overlays — not overwritten by plugin ZIP install. */
export const CUSTOM_PACK_SD_DIR = '0:/sys/nxt-user-custom'
