; nxt-save-rgb.g
;
; Persists the current RGB colour map, brightness, LED count and type so they
; survive a reboot. Writes /sys/nxt-rgb-colours.g, which nxt-user-overrides.g
; loads at boot (after the hardware block, so these win). Called by the nxt
; Status panel "Save" button via M98 P"nxt/nxt-save-rgb.g".
;
; Each colour is written component-by-component as a {R,G,B,W} literal so the
; output is always valid RRF array syntax regardless of firmware array
; formatting.

if { !inputs[state.thisInput].active }
    M99

var f = { "0:/sys/nxt-rgb-colours.g" }

echo >{var.f} { "; nxt-rgb-colours.g" }
echo >>{var.f} { "; Generated by the nxt Status panel (nxt-save-rgb.g). Do not edit by hand -" }
echo >>{var.f} { "; the Save button overwrites this file. Loaded from nxt-user-overrides.g" }
echo >>{var.f} { "; so the settings survive a reboot." }
echo >>{var.f} ""
echo >>{var.f} { "if { exists(global.nxtRGBIdle) }" }
echo >>{var.f} { "    set global.nxtRGBBri   = " ^ global.nxtRGBBri }
echo >>{var.f} { "    set global.nxtRGBType  = " ^ global.nxtRGBType }
echo >>{var.f} { "    set global.nxtRGBCount = " ^ global.nxtRGBCount }
var nxtRgbIdleLine = { "    set global.nxtRGBIdle  = {" ^ global.nxtRGBIdle[0] ^ "," ^ global.nxtRGBIdle[1] ^ "," ^ global.nxtRGBIdle[2] ^ "," ^ global.nxtRGBIdle[3] ^ "}" }
echo >>{var.f} { var.nxtRgbIdleLine }
var nxtRgbHomeLine = { "    set global.nxtRGBHome  = {" ^ global.nxtRGBHome[0] ^ "," ^ global.nxtRGBHome[1] ^ "," ^ global.nxtRGBHome[2] ^ "," ^ global.nxtRGBHome[3] ^ "}" }
echo >>{var.f} { var.nxtRgbHomeLine }
var nxtRgbProbeLine = { "    set global.nxtRGBProbe = {" ^ global.nxtRGBProbe[0] ^ "," ^ global.nxtRGBProbe[1] ^ "," ^ global.nxtRGBProbe[2] ^ "," ^ global.nxtRGBProbe[3] ^ "}" }
echo >>{var.f} { var.nxtRgbProbeLine }
var nxtRgbToolLine = { "    set global.nxtRGBTool  = {" ^ global.nxtRGBTool[0] ^ "," ^ global.nxtRGBTool[1] ^ "," ^ global.nxtRGBTool[2] ^ "," ^ global.nxtRGBTool[3] ^ "}" }
echo >>{var.f} { var.nxtRgbToolLine }
var nxtRgbRunLine = { "    set global.nxtRGBRun   = {" ^ global.nxtRGBRun[0] ^ "," ^ global.nxtRGBRun[1] ^ "," ^ global.nxtRGBRun[2] ^ "," ^ global.nxtRGBRun[3] ^ "}" }
echo >>{var.f} { var.nxtRgbRunLine }
var nxtRgbPauseLine = { "    set global.nxtRGBPause = {" ^ global.nxtRGBPause[0] ^ "," ^ global.nxtRGBPause[1] ^ "," ^ global.nxtRGBPause[2] ^ "," ^ global.nxtRGBPause[3] ^ "}" }
echo >>{var.f} { var.nxtRgbPauseLine }
var nxtRgbErrLine = { "    set global.nxtRGBErr   = {" ^ global.nxtRGBErr[0] ^ "," ^ global.nxtRGBErr[1] ^ "," ^ global.nxtRGBErr[2] ^ "," ^ global.nxtRGBErr[3] ^ "}" }
echo >>{var.f} { var.nxtRgbErrLine }
echo >>{var.f} { "    set global.nxtRGBReady = false" }

echo { "nxt: RGB settings saved. They will persist across reboots." }
