; nxt-save-rgb.g
;
; Persists RGB colour map, brightness and type across reboot.
; LED count (nxtRGBCount) is owned by Configuration → nxt-user-vars.g.
; Writes /sys/nxt-rgb-colours.g (loaded from nxt.g before post-colour M950).
; Called by the nxt Status panel Save button via M98 P"nxt/nxt-save-rgb.g".

if { !inputs[state.thisInput].active }
    M99

var f = { "0:/sys/nxt-rgb-colours.g" }

echo >{var.f} { "; nxt-rgb-colours.g" }
echo >>{var.f} { "; Generated by the nxt Status panel (nxt-save-rgb.g). Do not edit by hand -" }
echo >>{var.f} { "; the Save button overwrites this file. Loaded from nxt.g before M950" }
echo >>{var.f} { "; so the settings survive a reboot." }
echo >>{var.f} ""
echo >>{var.f} { "if { exists(global.nxtRGBCol) }" }
echo >>{var.f} { "    set global.nxtRGBBri   = " ^ global.nxtRGBBri }
echo >>{var.f} { "    set global.nxtRGBType  = " ^ global.nxtRGBType }

; One line per colour index (keeps each echo under the RRF line-length limit).
var i = 0
while { var.i < #global.nxtRGBCol }
    var c = global.nxtRGBCol[var.i]
    var line = { "    set global.nxtRGBCol[" ^ var.i ^ "] = {" }
    set var.line = { var.line ^ var.c[0] ^ "," ^ var.c[1] ^ "," ^ var.c[2] ^ "," ^ var.c[3] ^ "}" }
    echo >>{var.f} { var.line }
    set var.i = { var.i + 1 }

; Do not force nxtRGBReady=false — strip params already updated above; nxt.g / daemon M950 as needed.

echo { "nxt: RGB settings saved. They will persist across reboots." }
